# Generated by Django 4.2.15 on 2024-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('idCajas', models.AutoField(primary_key=True, serialize=False)),
                ('Saldo', models.FloatField()),
                ('Fecha_Apertura', models.DateField()),
                ('Fecha_Cierre', models.DateField(blank=True, null=True)),
                ('id_Tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Compra', models.CharField(max_length=45)),
                ('Total_Compra', models.CharField(max_length=45)),
                ('id_Persona', models.IntegerField()),
                ('idCajas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_DetCompra', models.AutoField(primary_key=True, serialize=False)),
                ('idCompra', models.IntegerField()),
                ('idProducto', models.IntegerField()),
                ('Cant_Comprada', models.CharField(max_length=45)),
                ('Prec_uni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_DetVta', models.AutoField(primary_key=True, serialize=False)),
                ('idVentas', models.IntegerField()),
                ('idProducto', models.IntegerField()),
                ('Cant_vendida', models.CharField(max_length=45)),
                ('Prec_uni', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_Persona', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Correo', models.CharField(max_length=45)),
                ('id_Tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=45)),
                ('Precio', models.FloatField()),
                ('Stock', models.FloatField()),
                ('idMarca', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id_Tipo', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVentas', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_venta', models.CharField(max_length=45)),
                ('Total_venta', models.FloatField()),
                ('Met_pagos', models.CharField(max_length=45)),
                ('id_Persona', models.IntegerField()),
                ('idCajas', models.IntegerField()),
            ],
        ),
    ]
