# Generated by Django 3.2.2 on 2024-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='Fecha_Apertura',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Fecha_Cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
