# Generated by Django 3.2.2 on 2024-09-23 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0003_auto_20240923_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='venta',
            name='Fecha_hora_venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('Transferencia', 'Transferencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.producto'),
        ),
    ]
