# Generated by Django 3.2.2 on 2024-09-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0004_auto_20240923_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Productos',
            new_name='ProductosTemp',
        ),
    ]
