# Generated by Django 3.2.2 on 2024-09-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0005_rename_productos_venta_productostemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='ProductosTemp',
            new_name='Productos',
        ),
    ]
