# Generated by Django 3.2.2 on 2024-09-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0007_venta_cantidad_vendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Total_venta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
